import type {
  Booking,
  BookingParticipant,
  BookingStatus,
  BookingType,
} from '../../types'
import { supabase } from './client'

// ---------------------------------------------------------------------------
// Insert shapes (id / timestamps are generated by the DB)
// ---------------------------------------------------------------------------

export type ParticipantInsert = Omit<BookingParticipant, 'id' | 'booking_id' | 'created_at'>

export interface BookingInsert {
  customer_id: string
  operator_id: string
  resort_id: string
  service_id: string
  availability_slot_id: string
  type: BookingType
  total_price: number
  currency?: string
  stripe_payment_intent_id?: string | null
  customer_notes?: string | null
  participants: ParticipantInsert[]
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function assertData<T>(data: T | null, error: { message: string } | null, context: string): T {
  if (error) throw new Error(`[bookings] ${context}: ${error.message}`)
  if (data === null) throw new Error(`[bookings] ${context}: no data returned`)
  return data
}

// The full booking select shape, joining participants
const BOOKING_SELECT = `
  *,
  booking_participants (*)
` as const

type BookingWithParticipants = Booking & { booking_participants: BookingParticipant[] }

/**
 * Creates a booking and its participants in two sequential inserts.
 * The booking is inserted first to obtain its generated ID, then participants
 * are batch-inserted referencing that ID.
 *
 * Returns the complete booking with participants attached.
 */
export async function createBooking(input: BookingInsert): Promise<BookingWithParticipants> {
  const { participants, ...bookingFields } = input

  // 1. Insert the booking row
  const { data: booking, error: bookingError } = await supabase
    .from('bookings')
    .insert({ ...bookingFields, status: 'pending' as BookingStatus })
    .select()
    .single()

  assertData(booking, bookingError, 'createBooking — booking insert')

  // 2. Batch-insert participants
  const participantRows = participants.map((p) => ({
    ...p,
    booking_id: booking!.id,
  }))

  const { error: participantsError } = await supabase
    .from('booking_participants')
    .insert(participantRows)

  if (participantsError) {
    throw new Error(`[bookings] createBooking — participants insert: ${participantsError.message}`)
  }

  // 3. Return the full record
  return getBookingById(booking!.id) as Promise<BookingWithParticipants>
}

/**
 * Returns a single booking with its participants by UUID.
 */
export async function getBookingById(id: string): Promise<BookingWithParticipants> {
  const { data, error } = await supabase
    .from('bookings')
    .select(BOOKING_SELECT)
    .eq('id', id)
    .single()

  return assertData(data, error, `getBookingById(${id})`) as BookingWithParticipants
}

/**
 * Returns all bookings (with participants) for a customer, newest first.
 */
export async function getBookingsByCustomer(customerId: string): Promise<BookingWithParticipants[]> {
  const { data, error } = await supabase
    .from('bookings')
    .select(BOOKING_SELECT)
    .eq('customer_id', customerId)
    .order('created_at', { ascending: false })

  return assertData(data, error, `getBookingsByCustomer(${customerId})`) as BookingWithParticipants[]
}

/**
 * Returns all bookings (with participants) for an operator, newest first.
 */
export async function getBookingsByOperator(operatorId: string): Promise<BookingWithParticipants[]> {
  const { data, error } = await supabase
    .from('bookings')
    .select(BOOKING_SELECT)
    .eq('operator_id', operatorId)
    .order('created_at', { ascending: false })

  return assertData(data, error, `getBookingsByOperator(${operatorId})`) as BookingWithParticipants[]
}

/**
 * Updates the status of a booking and returns the updated row.
 */
export async function updateBookingStatus(
  id: string,
  status: BookingStatus,
): Promise<BookingWithParticipants> {
  const { data, error } = await supabase
    .from('bookings')
    .update({ status })
    .eq('id', id)
    .select(BOOKING_SELECT)
    .single()

  return assertData(data, error, `updateBookingStatus(${id}, ${status})`) as BookingWithParticipants
}

/**
 * Looks up a booking by its QR token.
 *
 * The booking UUID is used directly as the QR token — it is unguessable and
 * sufficient for on-site check-in without a separate token column.
 */
export async function getBookingByQRToken(token: string): Promise<BookingWithParticipants> {
  return getBookingById(token)
}
